dist: bionic
language: python
python:
   - 3.7

install:
  - pip install -r requirements.txt
  - pip install .

script:
   - pytest


deploy:
  provider: pypi
  user: ${TWINE_USERNAME}
  password: ${TWINE_PASSWORD}
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
