dist: bionic
language: python
cache: pip
python:
   - 3.7

before_install:
  - sudo gem install github_changelog_generator &
  - pip install -r dev-requirements.txt
  - flake8 timemap
  - black --check timemap

install:
  - pip install .

script:
   - pytest
   - github_changelog_generator -t ${GITHUB_TOKEN} || true

deploy:
  - provider: releases
    api_key: ${GITHUB_TOKEN}
    file_glob: true
    file:
      - ./dist/*
      - CHANGELOG.md
    skip_cleanup: true
    on:
      tags: true
      branch: master

  - provider: pypi
    user: ${TWINE_USERNAME}
    password: ${TWINE_PASSWORD}
    skip_existing: true
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    on:
      tags: true
      branch: master

