dist: bionic
language: bash
cache: pip
services:
  - docker
python:
   - 3.7

before_install:
  - docker-compose build timemap-tests

script:
   - docker-compose run timemap-tests pytest

deploy:
  provider: pypi
  user: ${TWINE_USERNAME}
  password: ${TWINE_PASSWORD}
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
