dist: bionic
language: python
cache: pip
python:
   - 3.7

before_install:
  - pip install -r dev-requirements.txt
  - flake8 timemap
  - black --check timemap

install:
  - pip install .

script:
   - pytest


deploy:
  provider: pypi
  user: ${TWINE_USERNAME}
  password: ${TWINE_PASSWORD}
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
