dist: bionic
language: python
cache: pip
python:
   - 3.7

before_install:
  - pip install pipenv
  - pipenv install --dev
  - pre-commit run --all-files 

install:
  - pipenv install 

script:
   - pytest

deploy:
  provider: pypi
  user: ${TWINE_USERNAME}
  password: ${TWINE_PASSWORD}
  skip_existing: true
  distributions: "sdist bdist_wheel"
  on:
    tags: true
